# Use the Apache Web Server 
FROM httpd:latest 

# Giving my container a directory 
WORKDIR /files

# Add a file into it's directory 
COPY simplePage.html /files 


EXPOSE 80


#convert these into a .yml file for docker-compose features. 