# Use the Nginx Web Server 
FROM nginx:latest 

# Giving the container a place to hold Web Dev software
WORKDIR /user/share/nginx/html

# Add a file into it's html folder
COPY simplePage.html simplePage.html

# The port this container can be connected to
EXPOSE 80
#convert these into a .yml file for docker-compose features. 